### PR TITLE
fix: increase iceberg retries in integration tests

### PR DESCRIPTION
**Pull request by nicor88**
# Description

The iceberg retries integration test is the most problematic. Sometimes, it passes, and sometimes, it does not.
Currently the test dues 10 parallel inserts. The idea of this PR is to increase num_iceberg_retries to a value big enough, to allow the test to pass.

## Checklist

- [ ] You followed [contributing section](https://github.com/dbt-athena/dbt-athena#contributing)
- [ ] You kept your Pull Request small and focused on a single feature or bug fix.
- [ ] You added unit testing when necessary
- [ ] You added functional testing when necessary

### CODE REVIEW

**Comment by nicor88** [comment]
@mikealfare @colin-rogers-dbt FYI.

**Comment by nicor88** [comment]
> Input required and not supplied: aws-region
Integration tests seems failing because there is a missing region @mikealfare

**Comment by mikealfare** [comment]
> > Input required and not supplied: aws-region
> 
> Integration tests seem to be failing because there is a missing region @mikealfare
> 
> I believe that the issue is because [here](https://github.com/dbt-labs/dbt-athena/blob/4c3cbf4957667e885bffa42c13330ffa2e17e368/.github/workflows/integration-tests.yml#L62), my user (and every other user that contribute) don't have access to the variable. If the variable is set on your organization level, I cannot certenly use it. But if the variable is set on the repo level, I should be able to use it - as it used to be in the old dbt-athena repo.

The region is there. This looks like it's related to the aws-creds action. It started failing for me after last night for v2, but v4 passes. I have another PR that was affectd that has that fix. So when I get that merged in, I'll sync this PR and all should be fine

**Comment by nicor88** [comment]
@mikealfare any updates here? Integrations tests seems still not working, even after merging the latest from master

**Review by mikealfare — APPROVED** [review]

**Comment by mikealfare** [comment]
Turning it off and on again

**Pull request merged**
